[package]
name = "elements"
version = "0.19.2"
authors = ["Andrew Poelstra <apoelstra@blockstream.com>"]
description = "Library with support for de/serialization, parsing and executing on data structures and network messages related to Elements"
license = "CC0-1.0"
homepage = "https://github.com/ElementsProject/rust-elements/"
repository = "https://github.com/ElementsProject/rust-elements/"
documentation = "https://docs.rs/elements/"
edition = "2018"

[features]
default = [ "json-contract" ]
integration = [ "elementsd" ]

json-contract = [ "serde_json" ]
"serde" = [
    "bitcoin/serde",
    "secp256k1-zkp/use-serde",
    "actual-serde"
]
"fuzztarget" = []

[dependencies]
bitcoin = "0.29.1"
secp256k1-zkp = { version = "0.7.0", features = [ "global-context", "bitcoin_hashes" ] }
slip21 = "0.2.0"

# While this dependency is included in bitcoin, we need this to use the macros.
# We should probably try keep this one in sync with the bitcoin version,
# to avoid requiring two version of bitcoin_hashes.
bitcoin_hashes = "0.11.0"

# Used for ContractHash::from_json_contract.
serde_json = { version = "1.0", optional = true }

actual-serde = { package="serde", version = "1.0", features=["derive"], optional = true }

# This should be an optional dev-dependency (only needed for integration tests),
# but dev-dependency cannot be optional, and without optionality older toolchain try to compile it and fails
elementsd = {version = "0.6.0", features=["0_21_0","bitcoind_22_0"], optional = true }

[dev-dependencies]
rand = "0.8"
rand_chacha = "0.3"
serde_test = "1.0"
serde_json = "1.0"
serde_cbor = "0.8"   # older than latest version to support 1.41.1
ryu = "<1.0.5"
bincode = "1.3"
base64 = "0.13.0"

[[example]]
name = "pset_blind_coinjoin"

[[example]]
name = "raw_blind"

[[example]]
name = "tx"
