on: [push, pull_request]

name: Continuous integration

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: 1.58.0
            env:
              DO_FUZZ: true
          - rust: stable
            env:
              DO_INTEGRATION: true
          - rust: beta
          - rust: nightly
          - rust: 1.48.0
    steps:
      - name: Install test dependencies
        run: sudo apt-get install -y binutils-dev libunwind8-dev
      - name: Checkout Crate
        uses: actions/checkout@v2
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Running test script
        env: ${{ matrix.env }}
        run: ./contrib/test.sh
